apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-test
  labels:
    app: back
spec:
  replicas: 3
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine