apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-go-app-front
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: k8s-go-app-front
        imagePullPolicy: IfNotPresent #busca la imagen local antes de bajarla del hub
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-go-app-front
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend #label del pod, no deploy ni rs
  ports:
    - protocol: TCP
      port: 80 #puerto para exponer
      targetPort: 80 #puerto del contenedor, default:80