apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-test
  labels:
    app: back
spec:
  replicas: 3
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: back
spec:
  type: NodePort
  selector:
    app: back #label del pod, no deploy ni rs
  ports:
    - protocol: TCP
      port: 8085 #puerto para exponer
      targetPort: 80 #puerto del contenedor