apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-go-app
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: k8s-go-app
        imagePullPolicy: IfNotPresent #busca la imagen local antes de bajarla del hub
---
apiVersion: v1
kind: Service
metadata:
  name: backend-go-app
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend #label del pod, no deploy ni rs
  ports:
    - protocol: TCP
      port: 80 #puerto para exponer
      targetPort: 9090 #puerto del contenedor