apiVersion: v1
kind: Pod
metadata:
  name: podmanifest
spec:
  containers:
    - name: web-server
      image: nginx
      ports:
        - name: web
          containerPort: 82
          protocol: TCP